# Generated by Django 4.1.3 on 2022-11-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="occasion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
    ]
