# Generated by Django 4.1.3 on 2022-11-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="for_who",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Kim uchun"),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Rangi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="for_who",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.for_who",
                verbose_name="Kim uchun",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image1",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Birinchi rasm"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image2",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Ikkinchi rasm"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image3",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Uchinchi rasm"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image4",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Tortinchi rasm"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=254, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.type_category",
                verbose_name="Turi categoriysi",
            ),
        ),
        migrations.AlterField(
            model_name="type_category",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Turining nomi"),
        ),
    ]
