# Generated by Django 4.1.3 on 2022-12-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_count_title_alter_length_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.count",
                verbose_name="Nechtaligi",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.length",
                verbose_name="uzunligi",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.width",
                verbose_name="eni",
            ),
        ),
    ]
