# Generated by Django 4.1.3 on 2022-11-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_name_product_title_remove_product_occasion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="review_comment",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="review_title",
        ),
    ]
