# Generated by Django 4.1.3 on 2022-11-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="review_comment",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productreview",
            name="review_title",
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating_score",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                verbose_name="star",
            ),
        ),
    ]
