# Generated by Django 4.1.3 on 2022-11-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productreview_review_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="product_id",
        ),
        migrations.AddField(
            model_name="product",
            name="rating_star",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productreview",
            ),
            preserve_default=False,
        ),
    ]
