# Generated by Django 4.1.3 on 2022-11-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_productreview_product_id_product_rating_star"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="star",
            field=models.IntegerField(default=0, verbose_name="star"),
        ),
    ]
