# Generated by Django 4.1.3 on 2022-11-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productreview_star"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="rating_score",
        ),
    ]
