# Generated by Django 4.1.3 on 2022-11-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_rating_star_productreview_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="product_id",
            new_name="product",
        ),
    ]
