# Generated by Django 4.1.3 on 2022-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_gallery_sections_sectionscategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="fowerImg/"),
        ),
    ]
