# Generated by Django 4.1.3 on 2022-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Haqidaa"),
        ),
        migrations.AlterField(
            model_name="new",
            name="image",
            field=models.ImageField(upload_to="newsImg/", verbose_name="Rasm"),
        ),
    ]
