# Generated by Django 4.1.3 on 2022-11-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="status",
        ),
    ]
