# Generated by Django 4.1.3 on 2022-11-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="from_here",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="mode_cargo",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="to_here",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="type_cargo",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="volume_cargo",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="weight_cargo",
        ),
        migrations.DeleteModel(
            name="ContactImages",
        ),
        migrations.DeleteModel(
            name="Mode_cargo",
        ),
        migrations.DeleteModel(
            name="Type_cargo",
        ),
        migrations.DeleteModel(
            name="Volume_cargo",
        ),
        migrations.DeleteModel(
            name="Weight_cargo",
        ),
    ]
