# Generated by Django 4.1.3 on 2022-11-28 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0001_initial"),
        ("contact", "0002_remove_contact_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="from_here",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="order",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="to_here",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
