# Generated by Django 4.1.3 on 2022-11-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contact_from_here_contact_order_contact_to_here_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="order",
        ),
    ]
