# Generated by Django 4.1.3 on 2022-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_our_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="blog/")),
                ("description", models.TextField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Our_workers",
        ),
    ]
