# Generated by Django 4.1.3 on 2022-11-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_employee_delete_our_workers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="date_create",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="date_create",
            new_name="date_created",
        ),
    ]
