# Generated by Django 4.1.3 on 2022-11-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="temperatura",
        ),
        migrations.DeleteModel(
            name="TypeTemperatura",
        ),
    ]
