# Generated by Django 4.1.3 on 2022-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
