# Generated by Django 4.1.3 on 2022-12-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
    ]
