# Generated by Django 4.1.3 on 2022-11-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_temperatura_delete_typetemperatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="apps/order/"),
        ),
        migrations.AddField(
            model_name="order",
            name="images2",
            field=models.ImageField(blank=True, null=True, upload_to="apps/order/"),
        ),
        migrations.AddField(
            model_name="order",
            name="images3",
            field=models.ImageField(blank=True, null=True, upload_to="apps/order/"),
        ),
        migrations.DeleteModel(
            name="OrderImages",
        ),
    ]
