# Generated by Django 4.1.3 on 2022-11-28 09:26

import apps.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_number_product_alter_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="number_product",
        ),
        migrations.AddField(
            model_name="order",
            name="product_num",
            field=models.CharField(
                default=apps.order.models.random_string, max_length=1000
            ),
        ),
    ]
