# Generated by Django 4.1.3 on 2022-12-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_count_countcategory_and_more"),
        ("order", "0004_rename_user_order_acco_alter_orderitem_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="acco",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.product",
            ),
        ),
    ]
