# Generated by Django 4.1.3 on 2022-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="apps/order/"),
        ),
    ]
