# Generated by Django 4.1.3 on 2022-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_count_countcategory_and_more"),
        ("order", "0005_rename_acco_order_user_alter_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ManyToManyField(related_name="product", to="products.product"),
        ),
    ]
