# Generated by Django 4.1.3 on 2022-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(max_length=50, verbose_name="Full name"),
        ),
    ]
