# Generated by Django 4.1.3 on 2022-12-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Full name"),
        ),
    ]
