# Generated by Django 4.1.3 on 2022-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(default=1, max_length=50, verbose_name="Full name"),
            preserve_default=False,
        ),
    ]
